language: go
go:
- 1.5.1
env:
  - secure: "QxZXhM4iILiR3un+sOEMOzScOGpzeM3L+VPMeJnfSDW+Ikc17IuhxeJq/F7Im+YS2RkM6MPlY/HDW5j1PC0PVVFqhyars2YWC8S0J5voau8ZKSniIcaMHSAoj40xPNkwzcFnH6KE9LHgnmbioDCtfw2TegcJRGM/6qriLUby8lKxsPZ2pooJooXC/GpGkhGb6Le3964o+eOEj8cPyWQZ5UqWiM0K0MgE4OAe5eWBW1ZMKS3UgJgLHTpToaymqOl+Yec4XR830Jkc3QI8apfExH/c9OI+KexPk3h2zEKKORVXdKQhgeR3WphxN4Yy9au57gZOOVFfKWjObivFltzn6EOab/tcdBCD+fV+azIIpCMeD5Pg7u9FXQr9CJqbSJir7SlsDWtsgx5Ubkx6guX144/X/zKB0HaFrQhxZOxKDpGve9BzzU0EePJsan8MLcZizKiQPXNyaricuBiRgqslV6O7ikFtwqqvptseLfwY8yRoUtdSxHac7ULoI6K06Z1EILDLPjXzXLIv8eO7Ztzwi16owXZYjTkbDNrneM/zAb+86JwNqkpOStqlDJW6AXXVLVfw6yPWnyOXTTDW2koP2PNV40Mk/wJ8mtq8MSUkFGAaegbS3UZsMVr+LWmX/CorqMISADouIoiIhYzPL49Aa/A5JwHSkzGsekqeiNgKVxU="
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- PATH="$HOME/gopath/bin:$PATH"
- hack/coverage --coveralls
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: u4P/EosurXSWkdMP9UYk57nc1pP8KAn/a3Au+bImBY0CyvN8AVR2gpoSc8zf5yp0CjkdkkzlUzxK1DtEi8Gj06Oyb6iXeZBIA6Zc1xLD8LSIz+D6TYkjZUgL0TB9Dbwtt7M1VZEOtb3L5X/+vhOBzwrt8N54RKeo28Wdow1WbBnPI6f+pjCdG6WuVE903SUM0BCxrZpvfuRa0AbdSi6+vBaw+WBMg9fYfzbmGnNDBpqu8ohst1k6op8csJ+/1I6a3EIkJ/KHmhxeyQ15MaaQ4vOZCIzYsV3NgqKfwOPK8AwVj+AwJTN9yhowAh4S6jdNYInLJMS11cD3ZnNEQ8qwHCVixFLKA1lAZj4aadu5w5b9P2e0sDvwvNbQQh9SH1vgTZOi6o0zCvQA97NpzDV3KjyjjTyTQ+n9nninuZo64eQw6g/fRXx3fYc7QqIgNfFQHYusQVX2qFb8pBq6SIR9LA8eDAGw35vej/BFsW7vyGMykUrN5PicdadFEZvfr/JRc5eIAxEBzM7s57DE04xR75KWIVwfBplrLVLnqCgdJslUCIEm15sDAZ6br4/D03KasYDP9KSW099YzWkUYTIWNp+Vw5sfOGPHl/HVLO5i2hPpUGHib5xInFQvk6es/3GqGydN+mwhCAmQ51TF89LEUsPucBxTm1yV+PCxQU0vdcA=
  file:
  - dist/vcd-healthcheck.linux-amd64.tar.gz
  - dist/vcd-healthcheck.windows-amd64.zip
  on:
    tags: true
notifications:
  slack:
    secure: WQ1v6XL0he7nxhYUoXMCmQ7mxeSNQsz54z+yVw0LhDDIoWuhPmucV9es/yjTrebe7ZfrM8bmxYLxVVKgphQiXmZx/T76z3zZLNv/BfisLQeT2h1AVxHZ78UK8D3nTrdHM0rvosDv2dq6hC0WxtAZWEP/mGf3Nk+4dBLr4scddYyatApThCD50g1uX/kFs6a44OQ+NrxHFgWgN3NUkUDMMylhtd1mXmy1UDPlElc5h/tAspnrfOh4LwZeKl7lz1CdNDMJURwx8ZdVY22EvwPZISxCa4X6oYpoRoXt2zJ/JJE+H6ICwbo1nXbR6dMHnaZ0EWqgkIQUpGQixAdrsyBt8ddV+lrl6HzyMJcno7aae68oHyipJ5pv8/qQsbLlMlOPWCMeIXZpnzaE/dDLLy/3MZHUa4AWfv0xIHKJN7bhKz8dxfc8bqy/KHvIbbAAWUUBub2F9SRb4LK265skIZmIOLCgqAtKp3THwmhucJhLX4+Gt5ioCx6Cw/HDLD8g4uqR9eUPpRyLVn/ntEzERNPhqWzaHHesIVb3mNfOW3AtLkKfxtdICX4be5AGuhbvKljiFDyf7X582UrbfmfnV1Tjb8elDl8i9/bXFrrv+XtdFuvp2aioIZp81KX9BMVBXiDfugTVLjvwYuGxbxP75cym7jg1uYsMwvKduouQ+N9BRxE=
